version: 2
jobs:
  test:
    working_directory: ~/aeon
    docker:
    - image: circleci/clojure:lein-2.8.1
    - image: circleci/postgres:9.5.12-alpine # for integration test
    environment:
      TEST_JDBC_DB_URI: jdbc:postgresql://localhost:5432/postgres?loginTimeout=30&socketTimeout=900&tcpKeepAlive=true&user=postgres
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein do deps, cloverage --codecov
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: << checksum "project.clj" >>
      - run: git checkout https://github.com/skilbjo/markets-etl.git
      - run: lein do test, cljfmt check
      - run: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
  build:
    working_directory: ~/aeon
    docker:
    - image: circleci/clojure:lein-2.8.1
    environment:
      QUAY_ROBOT_USERNAME: skilbjo+robot
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: << checksum "project.clj" >>
      - setup_remote_docker
      - run: deploy/bin/publish-image

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
