#!/usr/bin/env bash
set -eou pipefail

# https://stackoverflow.com/questions/11952274/how-can-i-create-keystore-from-an-existing-certificate-abc-crt-and-abc-key-fil

# these are file paths
keyfile=$1
certfile=$2
password=${quandl_api_key}    # something random

# first we need to merge the keys into a pkcs12 keystore
openssl pkcs12 -export \
  -inkey $keyfile \
  -in $certfile \
  -out key_crt.p12 \
  -name key_crt \
  -password "pass:${password}"

keytool -importkeystore \
  -srckeystore key_crt.p12  \
  -srcstoretype pkcs12 \
  -srcstorepass "${password}" \
  -srcalias key_crt  \
  -destkeystore java_key_store \
  -deststoretype jks  \
  -deststorepass "${password}"
