#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app_name=$(basename $(dirname $dir))

docker run -it --rm \
  -p 8080:8080 \
  -e ro_db_jdbc_uri="$(echo $ro_db_jdbc_uri)" \
  "$app_name":dev bash
