#!/usr/bin/env bash
set -eoux pipefail

app=$(basename $(pwd) | sed -e 's/.git//')

check_if_running() {
  docker ps -a | grep compojure | awk '{print $1}' | xargs docker rm -f
}

remove_prior_image() {
  docker images | grep compojure | awk '{print $3}' | grep -v IMAGE | xargs docker rmi --force
}

set +e    # maybe first time deploying
check_if_running
remove_prior_image
set -e

## start
nohup ~/deploy/app/compojure/deploy/bin/run-docker >/tmp/compojure.log
