#!/usr/bin/env bash
set -eoux pipefail

app=$(basename $(pwd) | sed -e 's/.git//')

check_if_running() {
  ps | grep compojure.jar | grep -v grep | awk '{print $1}' | xargs kill -9
}

set +e    # maybe first time deploying
check_if_running
set -e

## start
nohup ~/deploy/app/compojure/deploy/bin/run-bare-metal >/tmp/compojure.log
