{:sources {:default :none
           :script   ["https://skilbjo.duckdns.org"
                      "https://skilbjo-sfo.duckdns.org"
                      "https://skilbjo-aws.duckdns.org"
                      "https://thirsty-northcutt-878096.netlify.app"
                      "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/"
                      "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/"
                      "http://192.168.2.2:8043"
                      "http://192.168.2.2:8048"
                      "http://192.168.2.2:8049"
                      "http://udoo:8049"
                      "http://pfsense2:8043"
                      "http://pfsense2:8048"
                      "http://pfsense2:8049"
                      "http://localhost:8080"
                      "http://localhost:8081"
                      "http://localhost:3449"
                      "http://docker:8080"
                      :unsafe-inline
                      :unsafe-eval]
           :style    ["https://skilbjo.duckdns.org"
                      "https://skilbjo-sfo.duckdns.org"
                      "https://skilbjo-aws.duckdns.org"
                      "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/"
                      "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/"
                      "https://fonts.googleapis.com/icon"
                      "http://192.168.2.2:8043"
                      "http://192.168.2.2:8048"
                      "http://192.168.2.2:8049"
                      "http://udoo:8049"
                      "http://pfsense2:8043"
                      "http://pfsense2:8048"
                      "http://pfsense2:8049"
                      "http://localhost:8080"
                      "http://localhost:8081"
                      "http://localhost:3449"
                      "http://docker:8080"
                      :unsafe-inline]
           :img      ["http://www.w3.org"
                      "data:"
                      "*"]
           :object   :none
           :font     ["http://skilbjo.duckdns.org"
                      "http://skilbjo-sfo.duckdns.org"
                      "http://skilbjo-aws.duckdns.org"
                      "https://fonts.googleapis.com/icon"
                      "https://fonts.gstatic.com/s/materialicons/v36/"
                      "https://fonts.gstatic.com/s/materialicons/v38/"
                      "https://fonts.gstatic.com/s/materialicons/v40/"
                      "https://fonts.gstatic.com/s/materialicons/"
                      "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/font/material-design-icons/"
                      "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/font/roboto/"
                      "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/fonts/"
                      "http://192.168.2.2:8043"
                      "http://192.168.2.2:8048"
                      "http://192.168.2.2:8049"
                      "http://pfsense2:8043"
                      "http://pfsense2:8048"
                      "http://pfsense2:8049"
                      "http://localhost:8080"
                      "http://localhost:8081"
                      "http://localhost:3449"
                      "http://docker:8080"
                      #_"data:"]
           :connect  ["http://skilbjo.duckdns.org"
                      "http://skilbjo-api.duckdns.org"
                      "http://192.168.2.2:8043"
                      "http://192.168.2.2:8048"
                      "http://192.168.2.2:8049"
                      "http://udoo:8049"
                      "http://pfsense2:8043"
                      "http://pfsense2:8048"
                      "http://pfsense2:8049"
                      "http://localhost:8080"
                      "http://localhost:8081"
                      "http://localhost"
                      "http://docker:8080"
                      "ws://localhost:8080"
                      "ws://localhost:8081"]
           :child    :self}}
