#!/usr/bin/env bash
set -euo pipefail

echo "Usage: $0 $ cat file-with-pretty.json | ./fixture-helper | pbcopy     " 1>&2
echo "  run $ lein test :only jobs.api-test  ... test will fail, copy/paste " 1>&2
echo "  to http://cljson.com/, and copy json output to file-with-pretty.json" 1>&2
echo "  run command, and paste output to test/fixtures/api.clj              " 1>&2

python3 -c "import json,sys; print(json.dumps(sys.stdin.read()).replace('\\\n','').replace('  ',''))"
