#!/usr/bin/env bash
set -eou pipefail

psql $docker_psql_uri -f ~/dev/markets-etl/dev-resources/test/ddl.sql
psql $docker_psql_uri -f ~/dev/aeon/dev-resources/test/aeon-ddl.sql
psql $docker_psql_uri -f ~/dev/aeon/dev-resources/test/insert-source-data.sql

cd ~/dev/markets-etl/dev-resources/make_environment/; ./upload-csv --table markets --database dev
