#!/usr/bin/env bash
set -eou pipefail

echo 'Go run a query on rds, select * from dw.portfolio and save results to csv'

aws s3 cp \
  --profile personal \
  ~/Desktop/file.csv s3://skilbjo-data/datalake/markets-etl/portfolio/file.csv
