#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" && cd "$dir"

source athena

get_users(){
  psql $aws_db_uri -AF',' -c 'select * from aeon.users' | ghead -n -1 >~/Downloads/file.csv
}

upload_markets_dim_to_s3(){
  aws s3 cp \
    --profile personal \
    ~/Downloads/file.csv s3://skilbjo-data/datalake/aeon/users/file.csv
}

verify_results(){
  query 'select * from aeon.users'
}

delete_artifacts(){
  rm ~/Downloads/file.csv
}

get_users \
  && upload_markets_dim_to_s3 \
  && verify_results \
  && delete_artifacts
